spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Jhansi@123
    url: jdbc:mysql://localhost:3306/sbms33
    username: root
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
    
server:
  port: 8081