spring:
  application:
    name: circut_Breaker
management:
  endpoints:
    web:
      exposure:
        include:  '*'
        
resilience4j.circuitbreaker:
    configs:
      Jhansi:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 100
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

  